displayName=Supply Balance
author=jazztothetwo
description=Tracks the long-term gain and loss of supplies through your bank
tags=bank,supplies,ironman,resources,tracker
version=
plugins=com.supplybalance.SupplyBalancePlugin
build=standard